version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker_runtime/rabbitmq_data:/var/lib/rabbitmq
    labels:
      description: "RabbitMQ server"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: svt
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./docker_runtime/postgres_data:/var/lib/postgresql/data
    labels:
      description: "PostgreSQL server"

  producer:
      build:
        context: ./src
        dockerfile: ./producer/Dockerfile
      depends_on:
        - rabbitmq
        - postgres
      environment:
        RABBITMQ_SERVER: rabbitmq  # RabbitMQ hostname within Docker network
        RABBITMQ_PORT: 5672
        RABBITMQ_USER: admin
        RABBITMQ_PASSWORD: admin
      # volumes:
      #   - ./src/producer:/app  # Mount your producer code inside the container
      labels:
        description: "TikTok Data Producer"