version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker_runtime/rabbitmq_data:/var/lib/rabbitmq
    labels:
      description: "RabbitMQ server"

  rabbitmq-bindings:
    build:
      context: ./src
      dockerfile: ./rabbitmq_bindings/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_SERVER: rabbitmq  # RabbitMQ hostname within Docker network
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
    labels:
      description: "RabbitMQ Bindings"

  postgres:
    image: postgres:13
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./docker_runtime/postgres_data:/var/lib/postgresql/data
    labels:
      description: "PostgreSQL server"

  producer:
      build:
        context: ./src
        dockerfile: ./producer/Dockerfile
      depends_on:
        - rabbitmq
        - postgres
      environment:
        RABBITMQ_SERVER: rabbitmq  # RabbitMQ hostname within Docker network
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
        RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      labels:
        description: "TikTok Data Producer"

  consumer:
      build:
        context: ./src
        dockerfile: ./consumer/Dockerfile
      depends_on:
        - rabbitmq
        - postgres
      environment:
        RABBITMQ_SERVER: rabbitmq  # RabbitMQ hostname within Docker network
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
        RABBITMQ_QUEUE_PERSISTENT: ${RABBITMQ_QUEUE_PERSISTENT}
        PGUSER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}
      labels:
        description: "TikTok Data Consumer"