version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker_runtime/rabbitmq_data:/var/lib/rabbitmq
    labels:
      description: "RabbitMQ server"

  postgres:
    image: postgres:13
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=svt_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker_runtime/postgres_data:/var/lib/postgresql/data
    labels:
      description: "PostgreSQL server"
