version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "${RABBITMQ_UI_PORT_MAP}:15672"
    volumes:
      - ./docker_runtime/rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    labels:
      description: "RabbitMQ server"

  rabbitmq-bindings:
    build:
      context: ./src
      dockerfile: ./rabbitmq_bindings/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_SERVER: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      RMQ_TASKS_EXCHANGE: ${RMQ_TASKS_EXCHANGE}
      RABBITMQ_HASHTAG_QUEUE: ${RABBITMQ_HASHTAG_QUEUE}
      RABBITMQ_VIDEO_BYTES_QUEUE: ${RABBITMQ_VIDEO_BYTES_QUEUE}
      RABBITMQ_EMBEDDINGS_QUEUE: ${RABBITMQ_EMBEDDINGS_QUEUE}
      RMQ_PRODUCER_TASKS_QUEUE: ${RMQ_PRODUCER_TASKS_QUEUE}
    labels:
      description: "RabbitMQ Bindings"

  postgres:
    image: pgvector/pgvector:pg14
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      PGUSER: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_MAP}:5432"
    volumes:
      - ./docker_runtime/postgres_data:/var/lib/postgresql/data
    labels:
      description: "PostgreSQL server"

  alembic:
    build:
      context: ./src
      dockerfile: ./postgresql/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/postgresql:/app/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    labels:
      description: "Alembic migration service"

  tasks-manager:
    build:
      context: ./src
      dockerfile: ./tasks_manager/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      rabbitmq-bindings:
        condition: service_completed_successfully
      postgres: 
        condition: service_healthy
      alembic:
        condition: service_completed_successfully
    environment:
      RABBITMQ_SERVER: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      RMQ_TASKS_EXCHANGE: ${RMQ_TASKS_EXCHANGE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./src/tasks_manager/main.py:/app/main.py
      - ./src/tasks_manager/manager.py:/app/manager.py
      - ./src/helpers:/app/helpers
      - ./src/postgresql:/app/postgresql
      - ./docker_runtime/logs:/app/logs
    labels:
      description: "Tasks Manager (Scheduler) for reccurent tasks"

  producer:
    build:
      context: ./src
      dockerfile: ./producer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      rabbitmq-bindings:
        condition: service_completed_successfully
    environment:
      RABBITMQ_SERVER: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      RMQ_PRODUCER_TASKS_QUEUE: ${RMQ_PRODUCER_TASKS_QUEUE}
    volumes:
      - ./src/producer/main.py:/app/main.py
      - ./src/producer/producer.py:/app/producer.py
      - ./src/helpers:/app/helpers
      - ./docker_runtime/logs:/app/logs
    labels:
      description: "TikTok Data Producer"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  consumer:
    build:
      context: ./src
      dockerfile: ./consumer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      rabbitmq-bindings:
        condition: service_completed_successfully
      postgres: 
        condition: service_healthy
      alembic:
        condition: service_completed_successfully
    environment:
      RABBITMQ_SERVER: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HASHTAG_QUEUE: ${RABBITMQ_HASHTAG_QUEUE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./src/consumer/main.py:/app/main.py
      - ./src/consumer/consumer.py:/app/producer.py
      - ./src/helpers:/app/helpers
      - ./src/postgresql:/app/postgresql
      - ./docker_runtime/logs:/app/logs
    labels:
      description: "Embeddings Consumer"

  embeddings-consumer:
    build:
      context: ./src
      dockerfile: ./consumer_embeddings/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      rabbitmq-bindings:
        condition: service_completed_successfully
      postgres: 
        condition: service_healthy
      alembic:
        condition: service_completed_successfully
    environment:
      RABBITMQ_SERVER: ${RABBITMQ_HOST} 
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      RABBITMQ_EMBEDDINGS_QUEUE: ${RABBITMQ_EMBEDDINGS_QUEUE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    labels:
      description: "TikTok Embeddings Consumer"
  
  video-processor:
    build:
      context: ./src
      dockerfile: ./video_processor/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      rabbitmq-bindings:
        condition: service_completed_successfully
    environment:
      RABBITMQ_SERVER: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      REGION: ${REGION}
      GOOGLE_APPLICATION_CREDENTIALS: /app/.ssh/google-credentials.json
    volumes:
      - ${HOME_DIR}/.ssh:/app/.ssh
    labels:
      description: "TikTok Multimodal Search Producer/Consumer"

  frontend:
    build:
      context: ./
      dockerfile: ./webapp/frontend/Dockerfile
    volumes:
      - ./webapp/frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
    labels:
      description: "React App"

  backend:
    build:
      context: ./
      dockerfile: ./webapp/backend/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      REGION: ${REGION}
      GOOGLE_APPLICATION_CREDENTIALS: /app/.ssh/google-credentials.json
    volumes:
      - ${HOME_DIR}/.ssh:/app/.ssh
    labels:
      description: "API backend for the frontend"

  nginx:
    image: nginx:latest
    volumes:
      - ./webapp/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: always

  ngrok:
    build:
      context: ./webapp/ngrok
      dockerfile: Dockerfile
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
    depends_on:
      - nginx
    ports:
      - ${NGROK_PORT_MAP}:4040
