"""added authors_reporting

Revision ID: 16b35331d1e2
Revises: f7382c647ead
Create Date: 2024-12-02 05:00:32.421934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b35331d1e2'
down_revision: Union[str, None] = 'f7382c647ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors_reporting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('digg_count', sa.Integer(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('heart_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', 'collected_at')
    )
    op.drop_index('follower_counts', table_name='authors')
    op.drop_column('authors', 'following_count')
    op.drop_column('authors', 'digg_count')
    op.drop_column('authors', 'heart_count')
    op.drop_column('authors', 'video_count')
    op.drop_column('authors', 'follower_count')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('authors', sa.Column('follower_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('video_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('heart_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('digg_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('following_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('follower_counts', 'authors', ['follower_count'], unique=False)
    op.drop_table('post_trends')
    op.drop_table('authors_reporting')
    # ### end Alembic commands ###
