"""Hashtag count

Revision ID: a350d835dadf
Revises: 4cd2361f4aeb
Create Date: 2024-11-10 16:59:51.454850

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a350d835dadf"
down_revision: Union[str, None] = "4cd2361f4aeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "authors", ["id"])
    op.add_column("challenges", sa.Column("hashtag_count", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "challenges", ["id"])
    op.drop_column("challenges", "view_count")
    op.drop_column("challenges", "video_count")
    op.create_unique_constraint(None, "music", ["id"])
    op.create_unique_constraint(None, "posts", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="unique")
    op.drop_constraint(None, "music", type_="unique")
    op.add_column(
        "challenges",
        sa.Column("video_count", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "challenges",
        sa.Column("view_count", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "challenges", type_="unique")
    op.drop_column("challenges", "hashtag_count")
    op.drop_constraint(None, "authors", type_="unique")
    # ### end Alembic commands ###
