"""Added posts_reporting table

Revision ID: b4cb226ac116
Revises: c79ecf4c5a69
Create Date: 2024-11-14 09:16:58.469334

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4cb226ac116"
down_revision: Union[str, None] = "c79ecf4c5a69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts_reporting",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("collect_count", sa.String(), nullable=True),
        sa.Column("comment_count", sa.String(), nullable=True),
        sa.Column("digg_count", sa.String(), nullable=True),
        sa.Column("play_count", sa.String(), nullable=True),
        sa.Column("repost_count", sa.String(), nullable=True),
        sa.Column("share_count", sa.String(), nullable=True),
        sa.Column(
            "inserted_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", "collected_at"),
    )
    op.drop_column("posts", "collect_count")
    op.drop_column("posts", "repost_count")
    op.drop_column("posts", "digg_count")
    op.drop_column("posts", "play_count")
    op.drop_column("posts", "share_count")
    op.drop_column("posts", "comment_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("comment_count", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "posts",
        sa.Column("share_count", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "posts",
        sa.Column("play_count", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "posts",
        sa.Column("digg_count", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "posts",
        sa.Column("repost_count", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "posts",
        sa.Column("collect_count", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_table("posts_reporting")
    # ### end Alembic commands ###
