"""added tables for extended hashtags

Revision ID: d9eaa08778c7
Revises: e09dfb2b3d86
Create Date: 2024-12-05 11:26:36.453381

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9eaa08778c7"
down_revision: Union[str, None] = "e09dfb2b3d86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "related_hashtags",
        sa.Column("antecedent_id", sa.String(), nullable=False),
        sa.Column("antecedent_title", sa.String(), nullable=False),
        sa.Column(
            "antecedent_support", sa.Numeric(precision=7, scale=5), nullable=False
        ),
        sa.Column("consequent_id", sa.String(), nullable=False),
        sa.Column("consequent_title", sa.String(), nullable=False),
        sa.Column(
            "consequent_support", sa.Numeric(precision=7, scale=5), nullable=False
        ),
        sa.Column("support", sa.Numeric(precision=7, scale=5), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=7, scale=5), nullable=False),
        sa.Column("lift", sa.Numeric(precision=7, scale=5), nullable=False),
        sa.Column(
            "inserted_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("antecedent_id", "consequent_id"),
    )

    op.execute(sa.schema.CreateSequence(sa.Sequence("rule_mining_log_id_seq")))

    op.create_table(
        "rule_mining_log",
        sa.Column(
            "id",
            sa.Integer(),
            server_default=sa.text("nextval('rule_mining_log_id_seq')"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column(
            "inserted_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rule_mining_log")
    op.execute(sa.schema.DropSequence(sa.Sequence("rule_mining_log_id_seq")))
    op.drop_table("related_hashtags")
    # ### end Alembic commands ###
