cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      first_name: Sir
      last_name: Admin
      logged_in: false
      password: $2b$12$0As/DHsxdNbfT6NFI3Tm4ue2G/LwzfbA8aNm6qck0BAHLjnj9KVke
      roles:
      - admin
